use_frameworks!

target 'WLVoiceConverter_Example' do
#  pod 'WLVoiceConverter', :path => '../'
pod 'WLVoiceConverter'

  target 'WLVoiceConverter_Tests' do
    inherit! :search_paths

    
  end
end
